djstripe/urls.py
"""
Wire this into the root URLConf this way::

    url(r'^stripe/', include('djstripe.urls', namespace="djstripe")),
    # url can be changed
    # Call to 'djstripe.urls' and 'namespace' must stay as is

Call it from reverse()::

    reverse("djstripe:subscribe")

Call from url tag::

    {% url 'djstripe:subscribe' %}

"""

from __future__ import unicode_literals
from django.conf.urls import patterns, url

from . import settings as app_settings
from . import views


urlpatterns = patterns("",
    url(
        r"^$",
        views.AccountView.as_view(),
        name="account"
    ),
    url(
        r"^subscribe/$",
        views.SubscribeFormView.as_view(),
        name="subscribe"
    ),
    url(
        r"^change/card/$",
        views.ChangeCardView.as_view(),
        name="change_card"
    ),
    url(
        r"^cancel/$",
        views.CancelView.as_view(),
        name="cancel"
    ),
    url(
        r"^history/$",
        views.HistoryView.as_view(),
        name="history"
    ),
    url(
        r"^a/sync_history/$",
        views.SyncHistoryView.as_view(),
        name="sync_history"
    ),
    url(
        app_settings.DJSTRIPE_WEBHOOK_URL,
        views.WebHook.as_view(),
        name="webhook"
    ),

)

djstripe/templates/djstripe/account.html
{% extends "payments/base.html" %}

{% block title %}Account{% endblock title %}

{% block content %}
    {{ block.super }}
<div class="container">
    <div class="row">
        <div class="col-12">
            <h2>Account Information</h2>
            {% include "djstripe/includes/_subscription_status.html" %}
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <p>
                Credit Card on file.
                <a class="btn btn-info" href="">Show card</a>
            </p>
        </div>
        <div class="col-6">
            <p class="pull-right">
                Next billed on {{ subscription.current_period_end }}
                <a class="btn btn-primary" href="{% url 'djstripe:subscribe' %}">Update credit card</a>
            </p>
        </div>
    </div>
    <div class="row">
        <div class="col-12">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Plan</th>
                        <th>Interval</th>
                        <th>Description</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    
                    {% for plan in plans %}
                        <tr>
                            <td>{{ plan.name }}</td>
                            <td>{{ plan.interval.title }}ly</td>
                            <td>{{ plan.description }}</td>
                            <td>
                                {% if plan.plan == subscription.plan %}
                                    Your plan
                                {% else %}
                                    Not your plan
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

{% block javascript %}
{{ block.super }}
<script>
    $(function() {
        $.post("{% url 'djstripe:sync_history' %}", function(data) {
            $('#history-table').html(data);
        });
    });
</script>
{% endblock javascript %}

djstripe/templates/djstripe/base.html
{% extends "base.html" %}
{% load static %}

{% block content %}
  <!-- Modal -->
  <div class="modal fade" id="in-progress">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4 class="modal-title">Server Update In-Progress <img src="{% static 'img/in-progress.gif' %}" /></h4>
        </div>
        <div class="modal-body">
            <div class="progress">
                <div class="progress-bar" style="width: 0%;"></div>
            </div>
        </div>

      </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
  </div><!-- /.modal -->
{% endblock %}

djstripe/templates/djstripe/history.html
{% extends "payments/base.html" %}

{% block title %}Payment History{% endblock title %}

{% block content %}
    {{ block.super }}
    <div id="history-table">
    {% include "djstripe/includes/_history_table.html" %}
    </div>
{% endblock content %}

{% block javascript %}
{{ block.super }}
<script>
    $(function() {
        $.post("{% url 'djstripe:sync_history' %}", function(data) {
            $('#history-table').html(data);
        });
    });
</script>
{% endblock javascript %}

djstripe/templates/djstripe/subscribe_form.html
{% extends "djstripe/base.html" %}

{% block title %}Subscription Form{% endblock title %}

{% block content %}
{{ block.super }}
<h2>Subscription Form</h2>

{% if error %}
    <div class="alert alert-error">{{ error }}</div>
{% endif %}
{% if view.error %}
    <div class="alert alert-error">{{ view.error }}</div>
{% endif %}

<form action="{% url 'djstripe:subscribe' %}" class="djstripe-payments"  data-stripe-key="{{ STRIPE_PUBLIC_KEY }}"  method="POST">
    {% csrf_token %}
    {{ form }}
    <input name="stripe_token" type="hidden" />
    <div class="form-actions">
        <!-- disable this when clicked -->
        <button type="submit" class="btn btn-primary">Subscribe</button>
    </div>
</form>


{% endblock content %}

{% block javascript %}
{{ block.super }}
<script src="//checkout.stripe.com/v2/checkout.js"></script>
<script text="text/javascript">
    $(function() {

        $('body').on("click", '.djstripe-payments button[type=submit]', function(e) {
          e.preventDefault();
          var $form = $(".djstripe-payments"),
              token = function(res) {
                $form.find("input[name=stripe_token]").val(res.id);

                $("button[type=submit]").attr("disabled", "true");
                $('#in-progress').modal({"keyboard": false})
                $('.progress-bar').animate({width:'+=100%'}, 2000);
                $form.trigger("submit");
              };

          StripeCheckout.open({
            key:         $form.data("stripe-key"),
            name:        'Payment Method',
            panelLabel:  'Add Payment Method',
            token:       token
          });

          return false;
        });
    });
</script>
{% endblock javascript %}